// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
console.log(process.env["DATABASE_URL"]);
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // point the seed command at our npm script so that TypeScript is
    // transpiled correctly and we avoid permission errors.
    // the package.json already has:
    //   "prisma:seed": "ts-node prisma/seed.ts"
    seed: "npm run prisma:seed",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
