### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "45b5065b4eb2bdbd410549c49aec70f4fcbe783f72a274b880cb1087306f325d0087306f020e112881fec4b107578a750584c93b4dad2023c017bcbe7c475086"
}


### Get me
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJiMWYwZmRjMy02YTNhLTRhZDYtOTk4Ni03YTM1MGU1NmQ3NzAiLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc3MzM3NDA5MSwiZXhwIjoxNzczMzc0OTkxfQ.T5YgWrYJ1j92MlzTzK03E9DmY5dNrXNgDBxWeoFak8t0KVh2N7s4ePxvQktrGHqZWQ_v0rDTydQyhJPR4voKfacsIfMVabECJINrUN_ZzTGyIerYQ8STr9dgyqlA2uawpvNPm60iYFubdNrtk90Loy5cxTo0xRAAf2TrZZXGsQQ1bFyyhtse-BtsWMj4dAstHBclFAfXUmRVys9BGYn-UrVygxhYdni6FWGs9kdi_j12Te1m-cCMF4YD_RWdIdm5XCpVXg5bn9GzktiwS2WGQb1Nj_bc-D532HAOSXuAU1wlZuXs4ZoE7vXcxeggs7EjQ2K7eeaVy9wLmxurv1isag


### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "8ca4ae956a9691a14a00f742f43062ed6cbd434717b1a56b1319180b53763548c6df09418d64b9c1169bf6765a1fb20d1c9c61dbb0b9cab00668f2112c26cae9"
}

### Logout All
POST http://localhost:3000/auth/logout-all
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJiMWYwZmRjMy02YTNhLTRhZDYtOTk4Ni03YTM1MGU1NmQ3NzAiLCJ0b2tlblZlcnNpb24iOjIsImlhdCI6MTc3MzQyODkzNywiZXhwIjoxNzczNDI5ODM3fQ.LJ6sq-JEFJmRV3XdTAs98bwKPkxnVinbXk_m7auILBUzHmrf1kNm3K4ER-a5ytGYnQ5UUUG0LhA2ujEIJ9V4hJqdmuuqDyLdSpTo_UzwvVPTpBmWuQ3EX-TBQNH63FnX8bBPeqAXgOKhhJBZagp_dX-3E3YXp3HPaxCqdP0CMI5sTQ2M_raOUCB_LP3C2nSipbEbkTDuJLl6T2k30uKKGhZd7-0-mNga2KourXg6-V7pYLAxCRAhAcX7lJ_HwpNQOxpZ-hmmGESKrHi9uOKerSImgAMZ7aYP7a-YqTdxDePzB6Zt1mZs2E0x8oCVNkKlJno9BgnGVk14JDulKR8d-Q