### Get Active Refresh Tokens
GET http://localhost:3000/refresh/active
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJiMWYwZmRjMy02YTNhLTRhZDYtOTk4Ni03YTM1MGU1NmQ3NzAiLCJ0b2tlblZlcnNpb24iOjMsImlhdCI6MTc3MzQyOTcwNSwiZXhwIjoxNzczNDMwNjA1fQ.AUDHpOaOt9OIjlDScaBWlI6gRwX2WZGAOOjMXQl8Civg3bn9rV1hir63EvgYkGXlGbVjec3T0P0bmzyBTNnkKMQ295eTSAjaa4ZJZdf2CrXyZUSRPCnaXoPq9MLdmH7qye5BMCFEjESFQ35ihK3NQEIWJsh-Wvf5_lM74S9aIynDHT-vuBFs4mbb_ab61F9PD6cxWiLGn9aBljIFoKeqklYaWIsK_A1sjqrMBLOZ3iGZpf9UMcbmvT_ePFHzdnl6nJ-5NSvP_8fUBnkStEAL0itWsM7nT6_cY4K7ox-1k6fhbMw7xAcR7KI_3JT6oWlXSXSKgEPPZ70OmJO_y4PAJA
